const profiles = {
  nabila: {
    name: "Nabila Ghaida Sigit", initials: "NGS", role: { en: "Informatics Engineering student", id: "Mahasiswi Teknik Informatika" }, location: "Tangerang",
    phone: "0856-7759-665", email: "ghaida.sigit@gmail.com", linkedin: "https://linkedin.com/in/nabila-ghaida-98900a378", linkedinLabel: "nabila-ghaida-98900a378", cv: "assets/CV_Nabila_Ghaida_Sigit.docx",
    summary: { en: "Informatics Engineering student with curiosity, strong learning drive, problem solving and analysis, self-reflection, perceptive understanding of situations and needs, open to new experiences and teamwork.", id: "Mahasiswi Teknik Informatika yang memiliki rasa ingin tahu, dorongan belajar yang kuat, kemampuan pemecahan masalah dan analisis, refleksi diri, pemahaman yang peka terhadap situasi dan kebutuhan, serta terbuka terhadap pengalaman baru dan kerja sama tim." },
    education: [{ period: "2025 — 2029", title: "S1 Teknik Informatika", place: "UIN Syarif Hidayatullah Jakarta" }, { period: "2021 — 2024", title: "SMA Al-Wildan 1", place: "Gading Serpong" }],
    experience: [{ period: "2026", title: { en: "K3 Division member", id: "Anggota Divisi K3" }, place: "PBAK UIN Syarif Hidayatullah Jakarta" }, { period: "2022", title: { en: "MPLS mentor", id: "Mentor MPLS" }, place: "SMA Al-Wildan 1" }, { period: "2022 — 2023", title: { en: "OSIS Social Division member", id: "Anggota Divisi Sosial OSIS" }, place: "SMA Al-Wildan 1" }],
    skills: [{ label: { en: "Hard skills", id: "Keahlian teknis" }, items: ["Microsoft Office", "Python"] }, { label: { en: "Soft skills", id: "Keahlian interpersonal" }, items: ["Team collaboration", "Empathy & emotional intelligence", "Decision making", "Critical thinking"] }, { label: { en: "Languages", id: "Bahasa" }, items: ["Indonesian — native", "English — active"] }]
  },
  najwa: {
    name: "Najwaturrohmah", initials: "N", role: { en: "Informatics Engineering student", id: "Mahasiswi Teknik Informatika" }, location: "Kota Jakarta Utara",
    phone: "+62 8212-110-7824", email: "Najwaaa.na007@gmail.com", linkedinLabel: "Najwa turrohmsh",
    summary: { en: "Independent, high work ethic, adaptive social interaction, effective communication, detail-oriented, hygiene and quality focused, eager to learn.", id: "Mandiri, memiliki etos kerja tinggi, adaptif dalam interaksi sosial, mampu berkomunikasi secara efektif, berorientasi pada detail, berfokus pada kebersihan dan kualitas, serta bersemangat untuk belajar." },
    education: [{ period: "2025 — present", title: "S1 Teknik Informatika", place: "UIN Syarif Hidayatullah Jakarta" }, { period: "2022 — 2025", title: "Pondok Pesantren Nurul Mukhlasin", place: "Average 80.00" }],
    experience: [{ period: "Oct — Nov 2025", title: { en: "Community service: “Membangun Warga Digital Cerdas dan Berkarakter”", id: "Pengabdian masyarakat: “Membangun Warga Digital Cerdas dan Berkarakter”" }, detail: { en: "Digital literacy and online gambling/loan awareness education.", id: "Edukasi literasi digital serta kesadaran tentang judi dan pinjaman online." } }, { period: "Jul 2022 — Feb 2024", title: { en: "Qur’an memorization of 10 juz", id: "Hafalan Al-Qur’an 10 juz" }, detail: { en: "Demonstrating discipline, focus, memory, stress management, integrity and work ethic.", id: "Menunjukkan kedisiplinan, fokus, daya ingat, manajemen stres, integritas, dan etos kerja." } }, { period: "June — August 2026", title: { en: "Committee: “Ready to Innovating, Solidarity, and Strive with Informatics”", id: "Kepanitiaan: “Ready to Innovating, Solidarity, and Strive with Informatics”" }, detail: { en: "K3/SOP, risk assessment, emergency response, medical logistics, sanitation and field response.", id: "K3/SOP, penilaian risiko, tanggap darurat, logistik medis, sanitasi, dan respons lapangan." } }],
    skills: [{ label: { en: "Languages", id: "Bahasa" }, items: ["English", "Indonesian", "Arabic"] }, { label: { en: "Digital tools", id: "Perangkat digital" }, items: ["Microsoft Word", "Excel", "PowerPoint", "Google Chrome", "Canva", "Python"] }, { label: { en: "Professional", id: "Profesional" }, items: ["Teamwork", "Communication", "Self-improvement", "Critical thinking"] }]
  },
  wisnu: {
    name: "Wisnu Hadi Sanicko", initials: "WHS", role: { en: "Food and beverage manager", id: "Manajer makanan dan minuman" }, location: "Jakarta Barat",
    phone: "085811237903", email: "iko.wisnu2003@gmail.com", linkedinLabel: "Iko Wisnu",
    summary: { en: "Dedicated manager in food and beverage, daily sales strategy, cash flow, recruitment/training, communication and problem solving, customer satisfaction, seeking more challenging career.", id: "Manajer makanan dan minuman yang berdedikasi, berpengalaman dalam strategi penjualan harian, arus kas, rekrutmen/pelatihan, komunikasi dan pemecahan masalah, serta kepuasan pelanggan; mencari karier yang lebih menantang." },
    education: [{ period: "2022 — 2029", title: "Teknik Informatika", place: "Universitas Islam Negeri Jakarta, Tangerang Selatan · GPA 3.6" }],
    experience: [{ period: "2021 — 2035", title: { en: "Manager", id: "Manajer" }, place: "Management Usaha Mie Ayam Bakso Pendy, Jl. Kemanggisan Ilir Raya", detail: { en: "Daily operations, taste/cleanliness/service standards; inventory, purchasing/stock opname and reducing food waste; daily cash flow and monthly sales reports.", id: "Operasional harian, standar rasa/kebersihan/pelayanan; inventaris, pembelian/stock opname dan pengurangan sisa makanan; arus kas harian dan laporan penjualan bulanan." } }],
    skills: [{ label: { en: "Hard skills", id: "Keahlian teknis" }, items: ["Inventory/stock management", "F&B operations", "Basic financial administration/cash reports", "POS applications", "Online delivery platforms such as GoFood/GrabFood"] }, { label: { en: "Soft skills", id: "Keahlian interpersonal" }, items: ["Leadership", "Time management", "Customer service", "Problem solving", "Teamwork", "Effective communication"] }, { label: { en: "Language", id: "Bahasa" }, items: ["Indonesian — fluent"] }]
  }
};

const translations = {
  en: { navHome: "Home", about: "Profile", education: "Education", experience: "Experience", skills: "Skills", contact: "Contact", summary: "Profile", contactMe: "Contact", download: "Download CV", based: "Based in", educationTitle: "Learning with intention.", experienceTitle: "Experience in practice.", skillsTitle: "Capabilities that matter.", contactTitle: "Let’s start a conversation.", contactCopy: "For opportunities, questions, or meaningful collaboration, please use the contact details below.", verified: "Verified CV information only.", home: "Home", eyebrow: "Three paths, one shared beginning", title: "Our Internship Portfolio.", intro: "Explore three independent profiles, shaped by learning, responsibility, and a readiness to contribute.", note: "Select a profile to view verified CV information.", profiles: "Profiles", choose: "Meet the people.", nabila: "Informatics Engineering student", najwa: "Informatics Engineering student", wisnu: "Food and beverage manager" },
  id: { navHome: "Beranda", about: "Profil", education: "Pendidikan", experience: "Pengalaman", skills: "Keahlian", contact: "Kontak", summary: "Profil", contactMe: "Hubungi", download: "Unduh CV", based: "Berbasis di", educationTitle: "Belajar dengan tujuan.", experienceTitle: "Pengalaman dalam praktik.", skillsTitle: "Keahlian yang berarti.", contactTitle: "Mari mulai percakapan.", contactCopy: "Untuk kesempatan, pertanyaan, atau kolaborasi yang bermakna, silakan gunakan detail kontak di bawah.", verified: "Hanya informasi CV terverifikasi.", home: "Beranda", eyebrow: "Tiga perjalanan, satu awal bersama", title: "Portofolio Magang Kami.", intro: "Jelajahi tiga profil terpisah yang dibentuk oleh pembelajaran, tanggung jawab, dan kesiapan untuk berkontribusi.", note: "Pilih profil untuk melihat informasi CV terverifikasi.", profiles: "Profil", choose: "Kenali mereka.", nabila: "Mahasiswi Teknik Informatika", najwa: "Mahasiswi Teknik Informatika", wisnu: "Manajer makanan dan minuman" }
};

let language = localStorage.getItem("portfolio-language") || "en";
const t = (key) => translations[language][key];
const text = (value) => typeof value === "string" ? value : value[language];

function header(active) {
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container header-inner"><a class="brand" href="index.html"><span class="brand-mark">OI</span><span>Our Internship Portfolio</span></a><nav class="desktop-nav" aria-label="Primary navigation"><a href="index.html">${t("navHome")}</a><a class="${active === "nabila" ? "active" : ""}" href="nabila.html">Nabila</a><a class="${active === "najwa" ? "active" : ""}" href="najwaturrohmah.html">Najwaturrohmah</a><a class="${active === "wisnu" ? "active" : ""}" href="wisnu.html">Wisnu</a></nav><div class="header-actions"><button class="language-toggle" id="language-toggle" type="button" aria-label="Switch language"><b>${language === "en" ? "EN" : "ID"}</b><span>/</span><span>${language === "en" ? "ID" : "EN"}</span></button><button class="menu-toggle" id="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open menu"><span></span><span></span></button></div></div><nav class="mobile-menu" id="mobile-menu" aria-label="Mobile navigation"><a href="index.html">${t("navHome")}</a><a href="nabila.html">Nabila</a><a href="najwaturrohmah.html">Najwaturrohmah</a><a href="wisnu.html">Wisnu</a></nav></header>`;
}

function profileMarkup(key) {
  const p = profiles[key];
  const itemList = (items) => items.map((item) => `<span>${item}</span>`).join("");
  return `${header(key)}<main id="main"><section class="profile-hero section"><div class="container profile-hero-grid"><div><p class="eyebrow">${text(p.role)}</p><h1>${p.name}</h1><p class="lead">${text(p.summary)}</p><div class="hero-actions"><a class="button button-primary" href="#contact">${t("contactMe")} <span aria-hidden="true">↗</span></a>${p.cv ? `<a class="button button-secondary" href="${p.cv}" download>${t("download")} <span aria-hidden="true">↓</span></a>` : ""}</div></div><div class="portrait-card"><span class="portrait-initials" aria-hidden="true">${p.initials}</span><span class="portrait-caption">${t("based")} ${p.location}</span></div></div></section>
  <section class="section section-border" id="about"><div class="container two-column"><div class="section-heading"><p class="eyebrow">01 / ${t("summary")}</p><h2>${text(p.role)}.</h2></div><div class="section-content"><p class="large-copy">${text(p.summary)}</p></div></div></section>
  <section class="section section-border" id="education"><div class="container"><div class="section-heading"><p class="eyebrow">02 / ${t("education")}</p><h2>${t("educationTitle")}</h2></div><div class="timeline">${p.education.map((e) => `<article class="timeline-item"><div class="timeline-date">${e.period}</div><div><h3>${e.title}</h3><p>${e.place}</p></div></article>`).join("")}</div></div></section>
  <section class="section section-border" id="experience"><div class="container"><div class="section-heading"><p class="eyebrow">03 / ${t("experience")}</p><h2>${t("experienceTitle")}</h2></div><div class="experience-grid">${p.experience.map((e, i) => `<article class="experience-card"><div class="experience-meta"><span>${e.period}</span><span class="card-number">0${i + 1}</span></div><h3>${text(e.title)}</h3>${e.place ? `<p class="organization">${e.place}</p>` : ""}${e.detail ? `<p>${text(e.detail)}</p>` : ""}</article>`).join("")}</div></div></section>
  <section class="section section-border" id="skills"><div class="container two-column"><div class="section-heading"><p class="eyebrow">04 / ${t("skills")}</p><h2>${t("skillsTitle")}</h2></div><div class="skills-content">${p.skills.map((g) => `<div class="skill-group"><h3>${text(g.label)}</h3><div class="skill-pills">${itemList(g.items)}</div></div>`).join("")}</div></div></section>
  <section class="section contact-section" id="contact"><div class="container contact-inner"><p class="eyebrow">05 / ${t("contact")}</p><h2>${t("contactTitle")}</h2><p>${t("contactCopy")}</p><div class="contact-links"><a class="contact-email" href="mailto:${p.email}">${p.email} <span aria-hidden="true">↗</span></a><a class="contact-phone" href="tel:${p.phone.replace(/[^\d+]/g, "")}">${p.phone} <span aria-hidden="true">↗</span></a>${p.linkedin ? `<a class="linkedin-link" href="${p.linkedin}" target="_blank" rel="noreferrer">LinkedIn ↗</a>` : `<span class="linkedin-link">${p.linkedinLabel}</span>`}</div></div></section></main><footer class="site-footer"><div class="container footer-inner"><span>© <span id="year"></span> ${p.name}</span><span>${t("verified")}</span><a href="#main" aria-label="Back to top">↑</a></div></footer>`;
}

function setup() {
  const page = document.body.dataset.page;
  if (page === "profile") document.querySelector("#app").innerHTML = profileMarkup(document.body.dataset.profile);
  document.documentElement.lang = language;
  document.querySelectorAll("[data-i18n]").forEach((el) => { const key = el.dataset.i18n.split(".").pop(); if (translations[language][key]) el.textContent = translations[language][key]; });
  document.querySelector("#year").textContent = new Date().getFullYear();
  document.querySelector("#language-toggle").addEventListener("click", () => { localStorage.setItem("portfolio-language", language === "en" ? "id" : "en"); location.reload(); });
  const menu = document.querySelector("#mobile-menu"), toggle = document.querySelector("#menu-toggle");
  toggle.addEventListener("click", () => { const open = menu.classList.toggle("open"); toggle.setAttribute("aria-expanded", String(open)); });
  menu.querySelectorAll("a").forEach((link) => link.addEventListener("click", () => { menu.classList.remove("open"); toggle.setAttribute("aria-expanded", "false"); }));
}
setup();
